TASKS = ['brush',
         'clean',
         'clip',
         'crush',
         'curl',
         'cut',
         'dig',
         'dispense',
         'drink',
         'dust',
         'flatten',
         'flip',
         'funnel',
         'grate',
         'grind',
         'hammer',
         'hang',
         'juice',
         'ladle',
         'lift',
         'lock',
         'mash',
         'mix',
         'open',
         'paint',
         'peel',
         'pick up',
         'plug in',
         'poke',
         'pound',
         'pour',
         'roll',
         'saute',
         'scoop',
         'scrape',
         'scratch',
         'screw',
         'scrub',
         'shake',
         'sharpen',
         'sift',
         'skewer',
         'skim',
         'slice',
         'spray',
         'squeegee',
         'squeeze',
         'stab',
         'stir',
         'straighten',
         'strain',
         'sweep',
         'tenderize',
         'till',
         'turn on',
         'handover']

TASKSING = ['brushing',
         'cleaning',
         'clipping',
         'crushing',
         'curling',
         'cutting',
         'digging',
         'dispensing',
         'drinking',
         'dusting',
         'flattening',
         'flipping',
         'funneling',
         'grating',
         'grinding',
         'hammering',
         'hanging',
         'juicing',
         'ladling',
         'lifting',
         'locking',
         'mashing',
         'mixing',
         'opening',
         'painting',
         'peeling',
         'pick-up',
         'plug-in',
         'poking',
         'pounding',
         'pouring',
         'rolling',
         'sauteing',
         'scooping',
         'scraping',
         'scratching',
         'screwing',
         'scrubbing',
         'shaking',
         'sharpening',
         'sifting',
         'skewering',
         'skimming',
         'slicing',
         'spraying',
         'squeegeeing',
         'squeezing',
         'stabbing',
         'stirring',
         'straightening',
         'straining',
         'sweeping',
         'tenderizing',
         'tilling',
         'turn-on',
         'handover']


OPENAI_API_KEY = "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"

OBJ_PROMPTS = {
    "shape": "Use 1-2 sentences to describe the shape of household object OBJ_CLASS in a detailed and scientific response:",
    "geometry": "Use 1-2 sentences to describe the geometry of household object OBJ_CLASS in a detailed and scientific response:",

    "use": "Use 1-2 sentences to describe the common use of household object OBJ_CLASS in a detailed and scientific response:",
    "func": "Use 1-2 sentences to describe the function of household object OBJ_CLASS in a detailed and scientific response:",

    "sim_shape": "Use 1-2 sentences to describe what household objects have similar shapes to OBJ_CLASS in a detailed and scientific response:",
    "sim_geo": "Use 1-2 sentences to describe what household objects have similar geometries to OBJ_CLASS in a detailed and scientific response:",

    "sim_func": "Use 1-2 sentences to describe what household objects have similar functions to OBJ_CLASS in a detailed and scientific response:",
    "sim_use": "Use 1-2 sentences to describe what household objects have similar uses to OBJ_CLASS in a detailed and scientific response:",
}

TASK_PROMPTS = {
    "sim_verb": "Use 1-2 sentences to describe what verbs are similar to TASK_CLASS in a detailed and scientific response:",
    "sem_verb": "Use 1-2 sentences to describe what verbs are semantically close to TASK_CLASS in a detailed and scientific response:",

    "sim_effect": "Use 1-2 sentences to describe what verbs achieve similar effects to 'TASK_CLASS an object' in a detailed and scientific response:",

    "use": "Use 1-2 sentences to describe what household objects can be used to TASK_CLASS in a detailed and scientific response:",
    "func": "Use 1-2 sentences to describe what household objects support the function of TASK_CLASS in a detailed and scientific response:",
}
